using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StandaloneApp.JSFrameworkGenerator
{
    public static class CompanyData
    {
        public static readonly IReadOnlyCollection<string> Companies = new[]
        {
            "15Five",
            "247 Techies",
            "37Coins",
            "40Tasks",
            "42 Floors",
            "43Layers",
            "8sec",
            "955 Dreams",
            "99 minutos",
            "99Gamers",
            "AISense",
            "API Fortress",
            "Abbeypost",
            "ActivityHero",
            "AdEspresso",
            "AdStage.io",
            "Ader",
            "Adphorus",
            "Aella Credit",
            "Affinity China",
            "Agfunder",
            "Aiotra",
            "AirPR",
            "AirSeed",
            "Aircall",
            "Airpair",
            "Airsorted",
            "Aksel Group",
            "Albert",
            "Alfred Labs",
            "Algolia",
            "All Trails",
            "Allay",
            "Almabase",
            "Alodokter",
            "Alpha Apps",
            "AlphaFlow",
            "Alpharank",
            "Alumnify",
            "Ambience Data",
            "Amicus",
            "Ample",
            "Andromium",
            "Andy OS",
            "AngelCam",
            "Animoca Brands",
            "Anyadir Education",
            "Anyroad",
            "AppSocially",
            "AppZen",
            "Apptopia",
            "Apptuto",
            "Apsalar",
            "Arcturus BioCloud",
            "Arka",
            "ArrowPass",
            "ArtCorgi",
            "Artiphon",
            "Artivest",
            "Asistia",
            "Astronomer",
            "Astroprint",
            "Attendant",
            "Auctio",
            "Audiodraft",
            "AuditFile",
            "Aumet",
            "AutoChilango",
            "AutoFi",
            "Autonomous",
            "Avanoo",
            "Avegant",
            "BIGcontrols",
            "BTCJam",
            "Babelverse",
            "BabyList",
            "Backlotcars",
            "Backstartup",
            "Backtype",
            "Backyard",
            "Baker Technologies",
            "Baloonr",
            "Bankons",
            "BarkBox",
            "Barn & Willow",
            "Beam",
            "Beeketing",
            "Beeline Bikes",
            "Behance",
            "BenRevo",
            "Bento",
            "Bespoke Post",
            "Besuccess",
            "BetterDoctor",
            "Betterworks",
            "Between",
            "Bglamor",
            "BidAway",
            "Bigfinite",
            "Billowby",
            "Billplz",
            "Binu",
            "BioBots",
            "BioFab",
            "Bisu",
            "Bitrefill",
            "Bizeebee",
            "Bizimply",
            "Blink Booking",
            "BlockCypher",
            "BlueLeaf",
            "Blueboard",
            "Bluefields",
            "Boatbound",
            "Bohemian Guitars",
            "Boletia",
            "Bombfell",
            "Book. Stay. Go.",
            "BoomTrain",
            "Boomerang",
            "Boon + Gable",
            "Boost Media",
            "Boostable",
            "Botanalytics",
            "BottlesTonight",
            "Bounty Hunter",
            "BoxGreen",
            "Boxbee",
            "Boxc",
            "Brainient",
            "Brandtrack",
            "Breaker",
            "Breather",
            "BrewPublik",
            "Bridg Payment Solutions",
            "BridgeUS",
            "BrightNest",
            "Brilliant",
            "Briskio",
            "Brushback",
            "Bstow",
            "Bucket",
            "Buenchef",
            "BugHerd",
            "Buildcon",
            "Bukalapak",
            "Burner",
            "BurstIQ",
            "Bustle",
            "CStorePro",
            "CalzaClick",
            "Cambrian Genomics",
            "Canva",
            "Caplinked",
            "Capy",
            "Carbon Health",
            "CardPlanet Solutions",
            "Cardlife",
            "Cardmunch",
            "CareGuide",
            "Caredox",
            "Carelulu",
            "Careport Health",
            "CargoBase",
            "Carousell",
            "Carreira Beauty",
            "Cashboard",
            "Cashie Commerce",
            "Catch that bus",
            "Catnip",
            "Celebrate",
            "Cellbreaker",
            "Cesanta",
            "Chain",
            "Chaldal",
            "Chalkable",
            "ChangeCoin",
            "ChangeJar",
            "ChannelMeter",
            "ChattingCat",
            "Check I'm Here",
            "Chewse",
            "ChinaNetCloud",
            "Chocotravlr",
            "Chouxbox",
            "Chromatik",
            "Cine+",
            "CinemaCraft",
            "CircleCI",
            "Cirrus Identity",
            "Civica Digital Mexico",
            "Cleanify",
            "Cleanly",
            "Click Mechanic",
            "Cloud Academy",
            "Cloud Admin",
            "Cloudability",
            "Cloudpeeps",
            "Clowder",
            "Club W",
            "CoContest",
            "Coach Market",
            "Cobalt",
            "CodeMentor",
            "CodeUpStart",
            "Codepicnic",
            "Cognuse",
            "Coinalytics",
            "Coinpip",
            "ColourLovers",
            "CommitChange",
            "Comparably",
            "Compstak",
            "Conekta",
            "Connected",
            "Connected2.me",
            "Conta Azul",
            "Contactually",
            "ContenTools",
            "Content Central",
            "Contently",
            "Cooleaf",
            "Cotiza y Contrata",
            "CourseReport",
            "Coursebase",
            "CraftCoffee",
            "CreditKarma",
            "Creopop",
            "Crocodoc",
            "Croissant",
            "Crowdfunder",
            "Crowdplat",
            "CucumberTown",
            "CultureAlley",
            "CultureMap",
            "Cuponomia",
            "Cursostotales",
            "DCHQ",
            "Dabee",
            "DailyMuse",
            "Dailyworth",
            "Dakwak",
            "DataRank",
            "Dataculture",
            "Datasembly",
            "Day2Life",
            "DayDayCook",
            "Dealflicks",
            "Descomplica",
            "DesignInc",
            "DigiSticky",
            "Dil Mil",
            "Disenia",
            "DocDoc",
            "Dojo Madness",
            "Dollar Beard Club",
            "Doughbies",
            "Doz",
            "Dr. Chrono",
            "Driven Labs",
            "DropShip",
            "Dropifi",
            "Dropsuite",
            "Dverse",
            "ELSA",
            "East Meet East",
            "Easy Ten",
            "Easy as Pi",
            "EasySize",
            "Easyship",
            "Eaze Solutions",
            "Edfa3ly",
            "Edools",
            "Edukart",
            "Eko",
            "El Wafayet",
            "Ematic Solutions",
            "Embroker",
            "Emburse",
            "Emprego Ligado",
            "Empreware",
            "Enchanted Diamonds",
            "Enplug",
            "Entrenaya",
            "EnvoyNow",
            "Epic!",
            "Eponym",
            "Equipboard",
            "EquityZen",
            "Erasmusinn",
            "Estately",
            "Ethic",
            "Etobb",
            "EverBill",
            "Eversnap Photography",
            "Evoz",
            "Evreka",
            "ExitRound",
            "Expansive Reality",
            "ExpenseBot",
            "Experiment",
            "Exploiter",
            "FIGS",
            "FabFitFun",
            "Fabelio",
            "Faception",
            "Facturama",
            "Famebit",
            "Fan.si",
            "Fanbridge",
            "Farmeron",
            "Fastwork",
            "Fave",
            "FeeFighters",
            "Feesheh",
            "Femeninas",
            "Fetchr",
            "Fi.TT",
            "Fiberead",
            "FileBoard",
            "FinCheck",
            "Fingertips Lab",
            "Finomial",
            "Firefly Space Systems",
            "FirstOpinion",
            "Firstjob.me",
            "Fitocracy",
            "Flashratings",
            "FlightFox",
            "Flipgive",
            "Float",
            "Floqq",
            "Flowtown",
            "FlyData",
            "Flycrates",
            "Flye",
            "Flyer",
            "Flywire",
            "FoodA",
            "Foodspotting",
            "Forrst",
            "FounderDating",
            "FoxType",
            "Freemit",
            "Front Row",
            "FullContact",
            "FullStack Academy",
            "Funnely",
            "Fy",
            "Game Closure",
            "Game Closure Inc",
            "Gather",
            "GazeMetrix",
            "Gazehawk",
            "Geckoboard",
            "Geekatoo",
            "Get Lighthouse",
            "Getagent",
            "Getlinks",
            "Giftcard Zen",
            "GinzaMetrics",
            "GitLab",
            "Givesurance",
            "GlamSt",
            "Glambot",
            "Glints",
            "GlobalID",
            "Gnowbe",
            "GoCoin",
            "GoSpotCheck",
            "Gogohire",
            "Goldbean",
            "Goldbely",
            "Goo Technologies",
            "Goodpeople",
            "Grab",
            "Gradible",
            "Graphicly",
            "Grata",
            "Greentoe",
            "GridCure",
            "Grillo",
            "Grove Collaborative",
            "Growbots",
            "Guidekick",
            "Gyft",
            "GymHit",
            "GymTrack",
            "Hacker Earth",
            "Hall.com",
            "HandStack",
            "HappyCo",
            "HappyFresh",
            "Hazel Lane",
            "HeTexted",
            "HeadOut",
            "HeartThis",
            "HeavyConnect",
            "Hedgeye",
            "Hello Bit",
            "Her",
            "Hinge",
            "Hipflat",
            "Hipster",
            "HireArt",
            "Hitsbook",
            "Holidog",
            "Home61",
            "HomeGP",
            "HomeLight",
            "Homebot",
            "Homeday",
            "Hornet",
            "HostTonight",
            "HoyPido",
            "Hubba",
            "Hubble",
            "Huinno",
            "HumTap",
            "Hunie",
            "Hykso",
            "I3zif",
            "IMRSV",
            "INZMO",
            "Iconfinder",
            "Import2",
            "InSparq",
            "Incluyeme.com",
            "Indemand",
            "Indinero",
            "Indio",
            "Influitive",
            "Infostellar",
            "Ingresse",
            "InnerSpace",
            "InnovAccer",
            "Insider",
            "InstaGIS",
            "InstaPaisa",
            "Instabeat",
            "Instamojo",
            "Interact.io",
            "Intercom",
            "Internmatch",
            "Interstate",
            "Investacrowd",
            "Iron Drone",
            "Ironclad",
            "Italist",
            "Iterable",
            "Ivee",
            "Jamalon",
            "Jeeran",
            "JetBay",
            "Jewelbots",
            "Job Pal",
            "Junglee Games",
            "Junomedical",
            "JÃ¡ Entendi",
            "Kaodim",
            "Karma",
            "KarmaLaunch",
            "KartRocket",
            "Keen Print",
            "Keen.io",
            "Kibin",
            "Kidblog",
            "Kidzjet",
            "Kiko Labs",
            "Kinedu",
            "Kinnek",
            "KiteReaders",
            "Kiwicrate",
            "Knotable",
            "Kodable",
            "Koemei",
            "KolayIK",
            "Kollecto",
            "Konfio",
            "Konnect-I",
            "Kudo",
            "LE TOTE",
            "LECO",
            "LIMK",
            "LabDoor",
            "Lagoa",
            "Lamusiquita",
            "Landmoda",
            "LaunchDarkly",
            "LaunchRock",
            "LaunchTrack",
            "Lawtova",
            "LeadGenius",
            "LeadScanner",
            "Lean Startup Machine",
            "Leapcure",
            "Leflair",
            "Legitmix",
            "Lenda",
            "Lettuce",
            "Lexity",
            "Life360",
            "LightBox",
            "Likeable Local",
            "LimeLight",
            "Linguatrip",
            "Linkdex",
            "Linte",
            "Lish",
            "Little Eye",
            "LittleFund",
            "Live Lovely",
            "Local Plant Source",
            "LocoMotive Labs",
            "Logic Roots",
            "Lottery.com",
            "LoveWithFood",
            "LoyaltyRefunds",
            "Lucid Chart",
            "Lumific",
            "M-vendr",
            "MBDC Media",
            "MMTG Labs",
            "MURAL",
            "MaestroConference",
            "Magnetis",
            "Magoosh",
            "Mailstrom",
            "MakeLeaps",
            "MakeSchool",
            "Makeably",
            "Maker.me",
            "Makerbot",
            "Mall IQ",
            "ManPacks",
            "Manicube",
            "ManyChat",
            "Markerly",
            "Mashvisor",
            "Mass Exchange",
            "Massive Bio",
            "Mattermark",
            "Mayvenn",
            "MeMeTales",
            "MeUndies",
            "Medialets",
            "Mejuri",
            "Melodics",
            "Melotic",
            "Mentimeter",
            "Merchbar",
            "Meshcrafts",
            "Metadata",
            "Metro Residences",
            "MexicoDestinos",
            "MightyText",
            "Mihaibao",
            "Milk and Honey",
            "Mindsnacks",
            "Mision Admision",
            "MisterBnB",
            "MixRank",
            "Mobile Action",
            "Mocavo",
            "Modest",
            "Mogul",
            "Moj.io",
            "MojiLala",
            "Monkimun",
            "MoonFruit",
            "Motion Math",
            "Mountary",
            "MoviePigs",
            "Movielala",
            "My Child",
            "MyCoffeeBox",
            "MyConvoy",
            "MyDoorman",
            "MyGengo",
            "MyGola",
            "MyHealthTeams",
            "MyPermissions",
            "MyTime",
            "Mytips",
            "NativeAd",
            "Nativetap.io",
            "Neighbor.ly",
            "Neuroware.io",
            "Neutun",
            "NewsWhip",
            "Nextravel",
            "NinjaBlocks",
            "Ninua",
            "NoRedInk",
            "Node.io",
            "Nomiku",
            "Nonnatech",
            "Noonswoon",
            "Novelistik",
            "Ntensify",
            "Nubity",
            "Nugit",
            "Nuve",
            "Nuvelar",
            "Nuzzel",
            "O.school",
            "OLSET",
            "Oddup",
            "Ohmconnect",
            "OhmniLabs",
            "Olev",
            "Omvana",
            "OnFarm",
            "OnePageCRM",
            "OneSpot",
            "Oneforty",
            "Onekloud",
            "OnlineTyari",
            "OpenSponsorship",
            "OrderCircle",
            "Ordoro",
            "Oree",
            "Otherinbox",
            "Outsite",
            "OwnLocal",
            "Oximity",
            "PICT",
            "PTA Networks",
            "PUSHTech",
            "Paidy",
            "Pal+",
            "Pangea",
            "Panoply",
            "Pantry",
            "Papaya",
            "Parkbench",
            "Partender",
            "Parting",
            "Partnered",
            "Paubox",
            "Pawprint",
            "Pay By Group",
            "PayClip",
            "PayDragon",
            "PayrollHero",
            "Peatix",
            "Penrose Studios",
            "PeopleFund",
            "Peoplise",
            "Perkhub",
            "Phenom",
            "Pic Collage",
            "Pick1",
            "Pigeonly",
            "Pijon",
            "Pilotly",
            "PingPad",
            "PixOwl",
            "Pixc",
            "PixelFish",
            "PlanGrid",
            "Plancast",
            "PlateJoy",
            "Platzi",
            "PlayCanvas",
            "Playbasis",
            "Plugger",
            "Plum",
            "PlusMargin",
            "Pluto AI",
            "Plympton Rooster",
            "Pocket Menu",
            "Pocket Supernova",
            "Podozi",
            "PogoSeat",
            "Pokkt",
            "PolicyPal",
            "Pop Up Archive",
            "PopXO",
            "Popsa",
            "Pose",
            "Power Supply Collective",
            "Powercore",
            "PredictionIO",
            "Prenetics",
            "Pressable",
            "PriceBaba",
            "Principly",
            "Printify",
            "Privy",
            "ProSky",
            "Proleads",
            "Promolta",
            "Proven",
            "Prynt",
            "Publishizer",
            "Punchd",
            "Puzzlium",
            "Pvgna",
            "Qimple",
            "Qishidai",
            "Qraved",
            "Qualio",
            "Quickli",
            "Quipper",
            "Qustn",
            "Qwil",
            "Rachio",
            "Rain",
            "Raisy",
            "Rankpeek",
            "Rapportive",
            "Raur",
            "Ready For Zero",
            "Realiteer",
            "Realty Shares",
            "Recurly",
            "Red Tricycle",
            "Reesio",
            "Regard",
            "Regresa Pronto",
            "Remark",
            "Remind",
            "Remix",
            "Remoov",
            "RentLord",
            "RepublicProject",
            "Resource",
            "ResultsOnAir",
            "Retailigence",
            "Revivn",
            "Riide",
            "Rikai Labs",
            "RingCaptcha",
            "Ripple",
            "RippleHire",
            "Rize",
            "Roam and Wander",
            "Rock Pamper Scissors",
            "Rocket",
            "RocketBolt",
            "RocketJourney",
            "Roho",
            "RolePoint",
            "Roost",
            "Ropanroll",
            "Rover",
            "RunRun.it",
            "Runnable",
            "Sabr.io",
            "SafeShepherd",
            "Saffron",
            "Sajilni",
            "Salido",
            "Sambaads",
            "Sampler",
            "Saucey",
            "Saygent",
            "ScentBird",
            "SchoolAdmissions",
            "Scopio",
            "ScoreData",
            "SearchMan",
            "Sellpad",
            "SendGrid",
            "SendHub",
            "Sentisis Analytics",
            "Sentry",
            "Senzari",
            "Settled",
            "ShareRoot",
            "Shareaholic",
            "Shelf",
            "Sheroes",
            "Shippo",
            "ShopGoMe",
            "Shopeando",
            "Shopline",
            "Shoppable",
            "Shoppr",
            "Shots Mobile",
            "Sickweather",
            "Siftery",
            "Sightly Enterprises",
            "Silkroad Images",
            "Silvernest",
            "Silverpush",
            "Simple",
            "SimplifiMed",
            "Simpliroute",
            "SimplyCook",
            "SimplyInsight",
            "Sinemia",
            "Siren Care",
            "SiteJabber",
            "Skeyecode",
            "SkillBridge",
            "SkimLinks",
            "Skygiraffe",
            "Slidebean",
            "Smart Bites",
            "Smile Identity",
            "Smove",
            "Smule",
            "Snapsheet",
            "Snips",
            "SocialDice",
            "SocialTables",
            "SocialTools",
            "SocialWire",
            "Socius",
            "Soldsie",
            "Solidarium",
            "Sonoma",
            "Sora",
            "Souktel",
            "SoundBetter",
            "Sourceeasy",
            "Spacee",
            "Sparkia",
            "Speedlancer",
            "Speek",
            "Spinnakr",
            "SpotHero",
            "Spottly",
            "Spoyl",
            "Springboard",
            "Sproutkin",
            "Sqoot",
            "Squadle",
            "StackShare",
            "StackSocial",
            "StartupHouse",
            "Statsbot",
            "Stitch",
            "Storemaven",
            "StormPulse",
            "Storyhunter",
            "Storytree",
            "Strapping",
            "StreamLoan",
            "Streem",
            "StudyPool",
            "StudySoup",
            "Stupeflix",
            "Styleseat",
            "Sunrise",
            "Sunshine",
            "Superhuman Labs",
            "SureBids",
            "Surefield",
            "Survmetrics",
            "Sverve",
            "Switch",
            "SwitchMe",
            "Synapp.io",
            "TRDATA",
            "Taamkru",
            "Tackl",
            "Tagbeat",
            "Tagove",
            "Talkable",
            "Talkdesk",
            "Tamatem",
            "TapFwd",
            "Tapastic",
            "Tappur",
            "Tappy",
            "Tapshot",
            "Tarefa",
            "Targeting Mantra",
            "TaskRabbit",
            "TeachStreet",
            "Tealet",
            "Teaman & Company",
            "Tech.eu",
            "Tees.co.id",
            "Telepathic",
            "Teleport",
            "TeliportMe",
            "Tello",
            "The Ticket Fairy",
            "TheAmazeApp",
            "TheIceBreak",
            "Thinglink",
            "ThinkParametric",
            "ThinkUp",
            "Thinknum",
            "Ticketbox",
            "Ticktate",
            "Tie Society",
            "Timbuktu",
            "Timely",
            "Tinfoil Security",
            "Tiny Post",
            "Tokyo Otaku Mode",
            "Torbit",
            "Toshl",
            "TotSpot",
            "TouristEye",
            "Tourkrub.co",
            "ToutApp",
            "Traction",
            "TradeBriefs",
            "Tradegecko",
            "Tradesy",
            "Traity",
            "Trance",
            "Transcriptic",
            "Transtutors",
            "Trocafone",
            "TrueLens",
            "TrustCloud",
            "Trusted Insight",
            "TrustedCompany.com",
            "Trym",
            "TuckerNuck",
            "Twilio",
            "Tynker",
            "UWisio",
            "UXCam",
            "Ubooly",
            "Udemy",
            "Uguru",
            "UmbaBox",
            "Unbisne",
            "Unbounce",
            "Uniko",
            "Unikrn",
            "Uninstall.io",
            "Unwind Me",
            "Up All Night",
            "Upcraft Club",
            "Upguard",
            "UseTrace",
            "VTS",
            "Vacayo",
            "VaiVolta",
            "Valor Water Analytics",
            "Vango",
            "Vayable",
            "Veduca",
            "Venzee",
            "Versly",
            "Versus",
            "Vessel",
            "Viajamex",
            "Vidcaster",
            "Video Pixie",
            "Viki",
            "ViralGains",
            "Virect",
            "Virool",
            "VisionX",
            "Visor",
            "Visually",
            "VivaReal",
            "Vizalytics",
            "VoidBrains",
            "Volta Industries",
            "Vonjour",
            "Vontrip",
            "Votizen",
            "Voxeet",
            "Vulcun",
            "Vungle",
            "WalkerCo",
            "WalletKit",
            "Wamova",
            "Wanderable",
            "Wanderu",
            "WashBox24",
            "Waygo",
            "We Are Onyx",
            "WeDidIt",
            "WePay",
            "WePlann",
            "WePow",
            "WeddingLovely",
            "Wedgies",
            "Welcu",
            "Wevorce",
            "Whale Path",
            "Whill",
            "Whim App",
            "WhoAPI",
            "WholeShare",
            "Wideo",
            "Wildfire",
            "WillCall",
            "WiseCommerce",
            "Wiselike",
            "Wishbird Experiences",
            "Wittlebee",
            "Womply",
            "WooMoo",
            "WorkAmerica",
            "WorkGenius",
            "WorkLife",
            "WorldShop",
            "Worq",
            "Worthix",
            "Wuzzuf",
            "XtGem",
            "YaSabe",
            "Yaxi",
            "YayPay",
            "YellowDig",
            "YesBoss",
            "YesGraph",
            "Yoderm",
            "YogaTrail",
            "YogoMe",
            "YouStake",
            "Youplus",
            "Your Superfoods",
            "ZBoard",
            "Zappli",
            "Zapr",
            "Zeemi.tv",
            "Zencoder",
            "Zenjob",
            "Zentist",
            "Zenysis",
            "Zesty",
            "ZipDial",
            "ZipMatch",
            "ZipZap",
            "ZoeMob",
            "Zolvers",
            "Zoomforth",
            "Zootrock",
            "Zowdow",
            "Zozi",
            "Zumata",
            "Zya",
            "Zyudly Labs",
            "deporPrivÃ©",
            "eCommHub",
            "eSpark",
            "eTraining",
            "eVenues",
            "enhance",
            "iDreamBooks",
            "iGrow",
            "iMoney",
            "mClinica",
            "medico",
            "mxHero",
            "myfavorito",
            "nurseVersity",
            "tagMonkey",
            "uBiome",
            "uTrack.tv",
        };
    }
}
