using StandaloneApp.JSFrameworkGenerator.Models;
using System.Collections.Generic;

namespace StandaloneApp.JSFrameworkGenerator
{
    static class FrameworkData
    {
        public static readonly IReadOnlyCollection<Framework> Frameworks = new[]
        {
            new Framework("Ampersand", "A highly modular, loosely coupled, non-frameworky framework for building advanced web applications."),
            new Framework("Angular", "One framework. Mobile and desktop."),
            new Framework("Angular.js", "HTML enhanced for web applications."),
            new Framework("AquaJS", "The friendly and fun JavaScript framework for your next web application."),
            new Framework("Aurelia", "A JavaScript framework for mobile and desktop with simple conventions and empowering creativity."),
            new Framework("Backbone", "Give your web application some Backbone with models, views, collections, and events."),
            new Framework("Canjs", "Can do JavaScript, better, faster, easier."),
            new Framework("Cell", "A self-driving JavaScript framework."),
            new Framework("Chaplin", "An architecture for JavaScript applications using the Backbone.js library."),
            new Framework("Choo", "Sturdy 4kb frontend JavaScript framework."),
            new Framework("Cycle.js", "A functional and reactive JavaScript framework for predictable code."),
            new Framework("Cyclow", "A reactive JavaScript framework for frontends."),
            new Framework("Derby", "MVC framework for making it easy to write realtime, collaborative applications that run in both Node.js and browsers."),
            new Framework("Derby-awesome", "A collection of awesome derby components."),
            new Framework("Diet", "A tiny, fast and modular node.js web framework. Good for making fast and scalable apps and apis."),
            new Framework("Dva", "React and redux based, lightweight and elm-style JavaScript framework. Inspired by elm and choo."),
            new Framework("Ember.js", "A JavaScript framework for creating ambitious web applications."),
            new Framework("Enyo", "A JavaScript application framework emphasizing modularity and encapsulation."),
            new Framework("Espresso.js", "A minimal JavaScript library for crafting user interfaces."),
            new Framework("Express", "Fast, unopinionated, minimalist JavaScript framework for Node.js."),
            new Framework("Feathers", "A real-time minimalist JavaScript framework for tomorrow's apps."),
            new Framework("Hapi", "A rich JavaScript framework for building applications and services. Write reusable application logic instead of spending time building infrastructure."),
            new Framework("Hyperapp", "1kb JavaScript library for building frontend applications."),
            new Framework("Inferno", "An extremely fast, React-like JavaScript library for building modern user interfaces."),
            new Framework("Jsblocks", "Better MV-ish JavaScript framework."),
            new Framework("Keo", "Functional stateless React components with Shadow DOM support."),
            new Framework("Knockout", "A JavaScript framework that makes it easier to create rich, responsive UIs."),
            new Framework("Koa", "Next generation JavaScript framework for Node.js."),
            new Framework("LiquidLava", "Transparent MVC framework for building user interfaces."),
            new Framework("LoopBack", "A highly-extensible, open-source JavaScript framework for quickly create dynamic end-to-end REST APIs."),
            new Framework("MEAN", "An opinionated fullstack JavaScript framework which simplifies and accelerates web application development."),
            new Framework("MERN", "A scaffolding tool which makes it easy to build isomorphic applications using Mongo, Express, React and NodeJS."),
            new Framework("Marionette", "A composite application library for Backbone.js that aims to simplify the construction of large scale JavaScript applications."),
            new Framework("Marionette", "Simplifies your Backbone application code with robust views and architecture solutions."),
            new Framework("Meteor", "An ultra-simple, database-everywhere, data-on-the-wire, pure JavaScript framework."),
            new Framework("Meteor", "The JavaScript App Platform. Build web applications that are a delight to use, faster than you ever thought possible."),
            new Framework("Mithril", "A JavaScript framework for building brilliant applications."),
            new Framework("Mithril.js", "A client-side MVC JavaScript framework. Light-weight, robust, and fast."),
            new Framework("Moon", "A minimal, blazing fast UI library."),
            new Framework("Nativescript", "Build truly native cross-platform apps with JavaScript."),
            new Framework("Nerv", "A blazing fast React alternative, compatible with IE8 and React 16."),
            new Framework("Onsen", "Mobile app development with HTML and JavaScript. Create beautiful and fast cross-platform apps with web components."),
            new Framework("Polymer", "Build modern applications using web components."),
            new Framework("Preact", "Fast 3KB React alternative with the same modern API. Components and Virtual DOM."),
            new Framework("RE:DOM", "Tiny 2KB turboboosted JavaScript library for creating user interfaces."),
            new Framework("Ractive", "Next-generation DOM manipulation."),
            new Framework("Radi", "Tiny (in size) JavaScript framework with no extra browser re-flows."),
            new Framework("Rax", "A universal React-compatible render engine."),
            new Framework("React", "A declarative, efficient, and flexible JavaScript library for building user interfaces."),
            new Framework("React", "A JavaScript library for building user interfaces. It's declarative, efficient, and extremely flexible. Works with a Virtual DOM."),
            new Framework("React-native", "A JavaScript framework for building native applications with React."),
            new Framework("Relay", "A JavaScript framework for building data-driven React applications."),
            new Framework("Restify", "JavaScript framework specifically meant for web service APIs."),
            new Framework("Riot", "React-like library, but with very small size."),
            new Framework("RiotJS", "Simple and elegant component-based UI library."),
            new Framework("Ripple", "A tiny foundation for building reactive views."),
            new Framework("Ripple Fullstack", "Modern fullstack JavaScript framework."),
            new Framework("Rivets", "Lightweight and powerful data binding and templating solution."),
            new Framework("RockJS", "The trusty JavaScript framework for old school guys."),
            new Framework("Sails.js", "Realtime MVC JavaScript framework for Node.js."),
            new Framework("Skate", "A JavaScript library designed to give you an augmentation of the web component specs focusing on a functional rendering pipeline, clean property and attribute semantics and a small footprint."),
            new Framework("Spine", "Lightweight MVC library for building JavaScript applications."),
            new Framework("Sproutcore", "A JavaScript framework for building blazing fast and innovative user experiences on the web."),
            new Framework("Stencil", "A simple, progressive web application and reusable web component compiler."),
            new Framework("Stimulus", "A modest JavaScript framework for the HTML you already have"),
            new Framework("Strudel", "Modern front-end framework for classical back-end websites."),
            new Framework("Svelte", "The magical disappearing UI library."),
            new Framework("Thorax", "An opinionated and battle tested JavaScript framework for building large scale web applications."),
            new Framework("Total.js", "Free JavaScript framework for building web applications using JavaScript, HTML and CSS. Node.js (HMVC) web application framework."),
            new Framework("Vue.js", "Intuitive, fast and composable MVVM for building interactive interfaces."),
            new Framework("Vue.js", "A progressive, incrementally-adoptable JavaScript framework for building UI on the web."),
            new Framework("Way.js", "Simple, lightweight, persistent two-way databinding.")
        };
    }
}
